# the host in which the playbook will be run
- hosts: all
  # in this example, we using a localhost, so this is needed
  # connection: local

  # the target user Ansible will impersonate when provisioning
  user: mgrenonville

  # this makes all tasks run with sudo by default
  become: true

  # additional variables
  vars:
    user: mgrenonville
    adoptopenjdk_package: adoptopenjdk-11-hotspot


  # roles are a way to group tasks; they will run in the sequence determined here
  roles:
    - base
    - ayltai.adoptopenjdk
    - windowmanager
    - mics
